{% set name = "opentelemetry-instrumentation-wsgi" %}
{% set version = "0.54b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_wsgi-{{ version }}.tar.gz
  sha256: 261ad737e0058812aaae6bb7d6e0fa7344de62464c5df30c82bea180e735b903

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.54b1
    - opentelemetry-semantic-conventions ==0.54b1
    - opentelemetry-util-http ==0.54b1

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
    - opentelemetry.instrumentation.wsgi
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-wsgi
  summary: WSGI Middleware for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
    - conda-forge/opentelemetry-api
    - conda-forge/opentelemetry-instrumentation
    - conda-forge/opentelemetry-semantic-conventions
    - conda-forge/opentelemetry-util-http
