{% set name = "opentelemetry-instrumentation-wsgi" %}
{% set version = "0.43b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_wsgi-{{ version }}.tar.gz
  sha256: 3a1cf045f7ccf04987a89cdd49eda93e9195de4c8b73be228a9e565ec3ab453c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.43b0
    - opentelemetry-semantic-conventions ==0.43b0
    - opentelemetry-util-http ==0.43b0
    # - opentelemetry-test-utils ==0.37b0
    # - opentelemetry-test-utils ==0.38b0
    # - opentelemetry-test-utils ==0.39b0
    # - opentelemetry-test-utils ==0.40b0
    # - opentelemetry-test-utils ==0.41b0
    # - opentelemetry-test-utils ==0.42b0
    # - opentelemetry-test-utils ==0.43b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-wsgi
  summary: WSGI Middleware for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
