{% set name = "opentelemetry-instrumentation-wsgi" %}
{% set version = "0.35b0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_wsgi-{{ version }}.tar.gz
  sha256: 79041b5e567734147768f3a40efbcbcb6234192bd8a307d2674462d4b68cb422

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7,<3.11
    - pip
    - hatchling
  run:
    - python >=3.7,<3.11
    - opentelemetry-api >=1.12,<2.dev0
    - opentelemetry-instrumentation ==0.35b0
    - opentelemetry-semantic-conventions ==0.35b0
    - opentelemetry-util-http ==0.35b0

    # - opentelemetry-test ==0.24b0
    # - opentelemetry-test-utils ==0.26b1
    # - opentelemetry-test-utils ==0.27b0
    # - opentelemetry-test-utils ==0.28b0
    # - opentelemetry-test-utils ==0.28b1
    # - opentelemetry-test-utils ==0.29b0
    # - opentelemetry-test-utils ==0.30b0
    # - opentelemetry-test-utils ==0.30b1
    # - opentelemetry-test-utils ==0.31b0
    # - opentelemetry-test-utils ==0.32b0
    # - opentelemetry-test-utils ==0.33b0

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-wsgi
  summary: WSGI Middleware for OpenTelemetry
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mariusvniekerk
